version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: food_order_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: food_order_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  activemq:
    image: rmohr/activemq:5.15.9
    container_name: food_order_activemq
    ports:
      - "61616:61616" # JMS port
      - "8161:8161"   # Web Console port
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin

volumes:
  mysql_data:
